### ISSUE TITLE
Implementar Vitest

### ISSUE THREAD

**Issue by jaenfigueroa** [POSTPUNK-TELETUBIES/rulesAdmin#190]
### Descripcion de la nueva implementacion

Realizar la instalación y configuración de vistest, que nos premitira cubrir el 100% de coverage en el proyecto.

### Sub tareas

- [x] Instalar y configurar Vitest en el proyecto 
      - #222 
- [x] Instalar React testing Library y JsDom
- [x] Documentar en issues
      - #195

### Tareas de test unitarios

- [x] #263 - **Aldair**
- [x] #234 - **Piero**
- [x] #235 - **Brenda**
- [x] #232 - **Jaen**

### Documentacion y/o libros que se usaron

- [Vitest](https://vitest.dev/)
- [React testing library](https://testing-library.com/)
- [JsDom](https://github.com/jsdom/jsdom)
