### ISSUE TITLE
Implementar React Auht Kit

### ISSUE THREAD

**Issue by jaenfigueroa** [POSTPUNK-TELETUBIES/rulesAdmin#205]
### Descripcion del problema a solucionar

El problema a resolver es implementar un sistema de autenticación seguro y eficiente en una aplicación web basada en React utilizando React Auth Kit. Actualmente, la aplicación carece de un mecanismo de autenticación y gestión de sesiones, lo que impide que los usuarios accedan a contenido protegido y limita la personalización de la experiencia del usuario en función de su identidad. Se necesita una solución que permita a los usuarios autenticarse de manera segura, acceder a áreas protegidas y gestionar sus sesiones de manera adecuada.

### Solución
React Auth Kit es una solución que proporciona un conjunto de herramientas y componentes para facilitar la implementación del sistema de autenticación en aplicaciones web basadas en React. 

### Sub tareas

- [x] Investigacion y lectura de la documentacion
- [x] Implementacion de React Auth Kit en rulesAdmin
   - [x] #225
   - [x] #226
   - [x] #227
   - [x] #228
- [x] Documentacion en discussions
  - #203 

### Documentacion
- [React Auth Kit](https://authkit.arkadip.dev/)

**Comment by Shadowrunner11** [comment]
Que decision se tomara respecto al anterior warpper de auth? si osi se debe borrar pero sera reemplazado por completo por react-auth-kit o se creara un context extediendoel de react-auth-kit?. 

Dependiendo de la decision donde estan los hallazgos q lo sustentan?
