### ISSUE TITLE
Agregar validaciones al formulario del login con yup

### ISSUE THREAD

**Issue by Shadowrunner11** [POSTPUNK-TELETUBIES/rulesAdmin#244]
Yup es una biblioteca de validación de JavaScript que permite definir y aplicar reglas de validación a los datos de entrada, como formularios. En el contexto de un formulario de inicio de sesión, la implementación de Yup puede garantizar que los datos ingresados por el usuario cumplan con ciertos criterios antes de enviarlos al servidor para su autenticación.

## Criterios de aceptación
- [x] La peticion de login no debe de dispararse si los campos contienen data no permitida
- [x] Debe existir feedback de los errores en español debajo de los campos afectados

### Descripción de como se realizo la implementación

En el proyecto, se llevó a cabo la implementación siguiendo un enfoque metódico . En primer lugar, se realizó un análisis exhaustivo de los requisitos y objetivos del proyecto para definir claramente el alcance. Luego, se diseñó un POC para contar con mayor claridad de implementación.

### Sub tareas

- [x] Agregar la funcionalidad

### Documentacion
- [Yup](https://github.com/jquense/yup/tree/master)
