### ISSUE TITLE
Optimizacion rutas

### ISSUE THREAD

**Issue by Shadowrunner11** [POSTPUNK-TELETUBIES/rulesAdmin#245]
### Descripción de la funcionalidad que se quiere implementar

Criterios de aceptaction
- [x] Con una conexion lenta , debe aparecer una pantalla de carga previa a cargar la pagina mientras se descarga el js de esa pagina
- [x] En desarrollo el watcher n debe hacer llamadas recursivas
- [x] Las rutas publcias deben estar separadas de las potenciales privadas

La carga de las paginas deben ser archivos aparte para evitar que el bundle final venga grande, ademas en prod el dist genera muchos archivos  q esto es otro problema separado pero realtivo a las rutas

### Descripción de como se realizo la implementación

Se uso el lazy loading para implementar code spliting 

### Sub tareas

- [x] Investigación y lectura de la documentación
- [x] Code spliting de las paginas
  -  #246 
- [x] Separacion de rutas privadas
- [x] Usar loaders en las rutas
- [x] Usar Await

### Enlaces de documentación y/o libros que se usaron

- [Complete Guide to React Lazy Loading and Code Splitting](https://www.copycat.dev/blog/react-lazy/)
