### ISSUE TITLE
Variante de login con particles

### ISSUE THREAD

**Issue by Shadowrunner11** [POSTPUNK-TELETUBIES/rulesAdmin#248]
### Descripción de la funcionalidad que se quiere implementar

Criterios de aceptacion
- [ ] Feature flag de  variante de login disponible
 
Se quiere q login pueda visualemnte tener  otra version con particles

### Sub tareas

- [ ] Investigación y lectura de la documentación
- [ ] Agregar la funcionalidad
- [ ] Documentación en [discussions](https://github.com/Shadowrunner11/rulesAdmin/discussions)
