### ISSUE TITLE
Implementar Dependabot

### ISSUE THREAD

**Issue by jaenfigueroa** [POSTPUNK-TELETUBIES/rulesAdmin#252]
### Descripción del problema

Recibir PR de actualizaciones de dependencias

### Descripción de como se solucionó

Aqui explica detalladamente...

### Sub tareas

- [X] Investigación y lectura de la documentación
- [ ] Refactorizar el codigo
- [ ] Documentación en [discussions](https://github.com/Shadowrunner11/rulesAdmin/discussions)

### Enlaces de documentación y/o libros que se usaron

- [Ejemplo 1](https://example.com)
- [Ejemplo 2](https://example.com)
