### ISSUE TITLE
Automatizar flujo de movimientos de issues en el tablero

### ISSUE THREAD

**Issue by jaenfigueroa** [POSTPUNK-TELETUBIES/rulesAdmin#255]
## Subtareas

- [x] Agregar los issue recien creados automaticamente al tablero "Sistema de reporteria SonarQube"
- [x] Mover los issues recien creados por defecto a "Backlog"
- [x] Mover los issues cerrados directamente a "Done"
- [x] Devolver los issues reabiertos a "In progress"
- [x] Cuando se asigna un revisador a un PR , el issue asociado se mueve a "in review - PR" 
- [x] Cuando se mergea un PR a la rama DEV, se mueve el issue asociado a "in Dev"  
- [x] Cuando se mergea un PR a la rama MAIN, los issue asociados se mueven a "In Main"
- [x] Cuando se cierra un PR sin mergear, el issue asociado vuelve a "In progress"
- [x] Cuando un PR se reabre, el issue asociado se mueve a "in review - PR"
- [x] Mostrar un mensaje al assignar  un usuario a una issue
- [x] Mostrar mensaje y etiquetar al culminar una issue
- [x] Mostrar mensaje y etiquetar cuando se asigna a un usuario en una issue
- [x] Mostrar mensaje al mergear un pr a la rama dev
- [x] Mostrar mensaje  y etiquetar cuando se asigna a un usuario como revisor de una pr

## Documentación y/o libros que se usaron
- [Using GitHub Actions for project management](https://docs.github.com/en/actions/managing-issues-and-pull-requests/using-github-actions-for-project-management)
- [Moving assigned issues on project boards](https://docs.github.com/es/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards)
- [Moving assigned issues on project boards](https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards)
- [Closing inactive issues](https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues)
- [Vincular un PR a una issue ](https://docs.github.com/es/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
