### ISSUE TITLE
Probot

### ISSUE THREAD

**Issue by jaenfigueroa** [POSTPUNK-TELETUBIES/rulesAdmin#257]
### Descripción del problema

Se necesita automatizar el flujo de trabajo en Github

### Sub tareas

- [x] Investigación y lectura de la documentación
- [x] Creación del POC
   - https://github.com/jaenfigueroa/poc-probot
- [x] Documentación en discussions
   - #258

### Enlaces de documentación y/o libros que se usaron

- [Probot Documentación](https://probot.github.io/docs/development/)
- [Organization Workflows](https://probot.github.io/apps/organization-workflows/)
- [Probot Github](https://github.com/probot/probot)
- [Documentación de Graphql](https://docs.github.com/graphql)
