### ISSUE TITLE
Actualizar las plantillas de issues

### ISSUE THREAD

**Issue by jaenfigueroa** [POSTPUNK-TELETUBIES/rulesAdmin#265]
### Descripción del problema

Implementar las nuevas etiquetas en las palntillas

### Descripción de como se solucionó

Aqui explica detalladamente...

### Sub tareas

- [ ] Investigación y lectura de la documentación
- [ ] Refactorizar el codigo
- [ ] Documentación en [discussions](https://github.com/Shadowrunner11/rulesAdmin/discussions)

### Enlaces de documentación y/o libros que se usaron

- [Ejemplo 1](https://example.com)
- [Ejemplo 2](https://example.com)
